### PR TITLE
Create a flexible external registry builder (#74)

### PR DESCRIPTION
**Pull request by dcowley**
The only options for configuring an external `DockerImageRegistry` are Docker Hub and Google Container Registry. We want the ability to support other registries, like [GitLab Container Registry](https://docs.gitlab.com/ee/user/packages/container_registry/).

This change introduces a flexible builder function to configure an external registry comprised of the following components:
1. Project
2. Namespace (optional)
3. Hostname (optional)

The external registry supports the following image naming convention:
```
<registry URL>/<namespace>/<project>
```
For example, these are all supported names for container images:
```
com.registry.example/mynamespace/myproject
```
```
com.registry.example/myproject
```
```
mynamespace/myproject
```

### CODE REVIEW

**Comment by dcowley** [comment]
Hi @Stexxe, @e5l

Would you please review this change when you have a chance?

Thanks

**Comment by dcowley** [comment]
Hi @Stexxe, @e5l

Please review this PR?

Thanks

**Review by e5l — APPROVED** [review]
lgtm

**Comment by e5l** [comment]
Hty @dcowley, thanks for the PR. Merged

**Pull request merged**
